pipeline:
  build:
    image: debian # not using alpine so we get a glibc build
    commands:
      - apt update
      - apt install -y curl jq xz-utils libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev

      # Install Zig
      - curl $(curl https://ziglang.org/download/index.json | jq -r '.master."x86_64-linux".tarball') -o /tmp/zig.tar.xz
      - tar xf /tmp/zig.tar.xz --directory=/tmp
      - export PATH="$(echo /tmp/zig-*):$PATH"

      - zig build test
      - zig build -Doptimize=ReleaseFast

  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://mzte.de/git
      api_key:
        from_secret: forgejo_key
      title: tag-${CI_COMMIT_TAG}
      files: zig-out/bin/confgen
    when:
      event: tag
