steps:
  build:
    image: git.mzte.de/lordmzte/zig-build
    commands:
      - apt update
      - apt install -y ca-certificates libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev libfuse3-dev libfuse3-3

      - zig fmt --check .
      - zig build test
      - zig build -Doptimize=ReleaseFast

  packages:
    image: alpine
    commands:
      - apk add zip
      - cd zig-out
      - zip -r ../confgen-linux-x86_64.zip .
    when:
      event: tag

  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://git.mzte.de
      api_key:
        from_secret: forgejo_key
      title: tag-${CI_COMMIT_TAG}
      files: confgen-linux-x86_64.zip
    when:
      event: tag
