pipeline:
  build:
    image: eloitor/zig:master
    commands:
      - apk add luajit-dev
      - zig build test
      - zig build -Doptimize=ReleaseFast

  publish:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://mzte.de/git
      api_key:
        from_secret: forgejo_key
      title: tag-${CI_COMMIT_TAG}
      files: zig-out/bin/confgen
    when:
      event: tag
