on:
  push:
    tags: 'v.*'

jobs:
  release:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Build
        run: |
          apt update
          apt install -y ca-certificates libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev libfuse3-dev libfuse3-3

          zig build -Doptimize=ReleaseFast

      - name: Zip
        run: |
          mkdir release
          cd zig-out
          zip -r ../release/confgen-linux-x86_64.zip .

      - name: Upload
        uses: actions/forgejo-release@v1
        with:
          direction: upload
          release-dir: dist/release
