name: Release
on:
  push:
    tags: 'v.*'

jobs:
  release:
    runs-on: docker
    needs: build
    steps:
      - name: Zip
        run: |
          cd zig-out
          zip -r ../confgen-linux-x86_64.zip .
      - name: Upload
        uses: forgejo/upload-artifact@v4
        with:
          name: confgen-linux-x86_64.zip
          path: confgen-linux-x86_64.zip
