on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: docker-x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: actions/setup-zig@v2
        with:
          version: 0.14.0

      - name: Setup Packages
        run: |
          apt update
          apt install -y ca-certificates libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev libfuse3-dev libfuse3-3 zip

      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast

      - name: Zip
        run: |
          mkdir release
          cd zig-out
          zip -r ../release/confgen-linux-x86_64.zip .

      - name: Upload
        uses: actions/forgejo-release@v1
        with:
          direction: upload
          release-dir: release
          token: ${{ env.GITHUB_TOKEN }}
