on: [push, pull_request]

jobs:
  test:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: actions/setup-zig@v2
        with:
          version: 0.15.1

      - name: Setup Packages
        run: |
          apt update
          apt install -y ca-certificates libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev libfuse3-dev libfuse3-3

      - name: Test
        run: |
          zig fmt --check .
          zig build test
