on: [push]

jobs:
  test:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: https://github.com/goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Test
        run: |
          apt update
          apt install -y ca-certificates libluajit-5.1-dev libluajit-5.1-2 liblua5.1-0-dev libfuse3-dev libfuse3-3

          zig fmt --check .
          zig build test
